- name: Setup Flutter project structure
  run: flutter create . --platforms=ios --org com.shinn

- name: Get dependencies
  run: flutter pub get

- name: Install CocoaPods
  run: |
    cd ios
    pod install
    cd ..

- name: Build iOS (unsigned)
  run: flutter build ios --release --no-codesign
